import 'vfonts/Lato.css'
import 'vfonts/FiraCode.css'
import 'virtual:svg-icons-register'
import './index.css'
import './transition.css'
import '@/icons/iconfont/iconfont.css'
import 'qweather-icons/font/qweather-icons.css'
